[07:36:18 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:198:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:26:47 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\auth.js:284\n                const fs = require('fs');\n                      ^\n\nSyntaxError: Identifier 'fs' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:48:20)","name":"SyntaxError","message":"Identifier 'fs' has already been declared"}
[08:26:52 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\auth.js:288\n                const fs = require('fs');\n                      ^\n\nSyntaxError: Identifier 'fs' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:48:20)","name":"SyntaxError","message":"Identifier 'fs' has already been declared"}
[08:27:09 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\auth.js:288\n                const fs = require('fs');\n                      ^\n\nSyntaxError: Identifier 'fs' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:48:20)","name":"SyntaxError","message":"Identifier 'fs' has already been declared"}
[08:27:21 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\auth.js:288\n                const fs = require('fs');\n                      ^\n\nSyntaxError: Identifier 'fs' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:48:20)","name":"SyntaxError","message":"Identifier 'fs' has already been declared"}
[08:28:38 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\auth.js:289\n                const fs = require('fs');\n                      ^\n\nSyntaxError: Identifier 'fs' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:48:20)","name":"SyntaxError","message":"Identifier 'fs' has already been declared"}
[08:28:43 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\auth.js:289\n                const fs = require('fs');\n                      ^\n\nSyntaxError: Identifier 'fs' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:48:20)","name":"SyntaxError","message":"Identifier 'fs' has already been declared"}
[08:28:57 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:29:01 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:29:08 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:32:59 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:39:05 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:39:11 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:39:29 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:40:53 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:41:04 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:42:28 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:42:44 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[08:42:50 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:261:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:11:21 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:106:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[09:17:50 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:18:09 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:18:22 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:18:28 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:19:11 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:22:04 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:23:30 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[09:54:41 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:41:38 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:41:51 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:41:53 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:41:58 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:42:16 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:42:21 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:45:34 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:45:37 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:46:22 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:46:29 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[10:46:44 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:12:31 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:13:10 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:14:01 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:14:02 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:14:25 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:14:51 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:14:57 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:15:31 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:15:31 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[11:15:46 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:263:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:24:40 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\shop.js:137:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[12:25:56 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:26:14 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:26:33 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[13:15:15 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[13:30:04 19/07/2025] [ERROR] Session store error | Meta: {"stack":"Error: Error finding kgIqJmozg1vLu06wlMSuHiSv_eq8MVI6: getaddrinfo ENOTFOUND cluster0-shard-00-00.unzei.mongodb.net\n    at D:\\lab_node\\node_modules\\connect-mongodb-session\\index.js:143:19","name":"Error","message":"Error finding kgIqJmozg1vLu06wlMSuHiSv_eq8MVI6: getaddrinfo ENOTFOUND cluster0-shard-00-00.unzei.mongodb.net"}
[14:23:28 19/07/2025] [ERROR] Session store error | Meta: {"stack":"Error: Error finding kgIqJmozg1vLu06wlMSuHiSv_eq8MVI6: getaddrinfo ENOTFOUND cluster0-shard-00-00.unzei.mongodb.net\n    at D:\\lab_node\\node_modules\\connect-mongodb-session\\index.js:143:19\n    at runNextTicks (node:internal/process/task_queues:65:5)\n    at process.processTimers (node:internal/timers:526:9)","name":"Error","message":"Error finding kgIqJmozg1vLu06wlMSuHiSv_eq8MVI6: getaddrinfo ENOTFOUND cluster0-shard-00-00.unzei.mongodb.net"}
[14:42:01 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[14:42:52 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[14:43:20 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:21:59 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:22:05 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:22:11 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:22:17 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:22:34 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:23:17 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[16:30:34 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:30:09 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:30:15 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:30:17 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:30:46 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:31:18 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:34:50 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:35:00 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:35:02 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:35:23 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:35:27 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:35:28 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:35:54 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:36:02 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:42:03 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:42:05 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:42:21 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:42:39 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:42:56 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:00 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:04 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:24 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:36 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:41 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:46 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:43:51 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\controllers\\admin.js:2597\n                } else {\n                  ^^^^\n\nSyntaxError: Unexpected token 'else'\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:6:25)","name":"SyntaxError","message":"Unexpected token 'else'"}
[20:43:52 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\controllers\\admin.js:2597\n                } else {\n                  ^^^^\n\nSyntaxError: Unexpected token 'else'\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:6:25)","name":"SyntaxError","message":"Unexpected token 'else'"}
[20:43:59 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\controllers\\admin.js:2597\n                } else {\n                  ^^^^\n\nSyntaxError: Unexpected token 'else'\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:6:25)","name":"SyntaxError","message":"Unexpected token 'else'"}
[20:43:59 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\controllers\\admin.js:2597\n                } else {\n                  ^^^^\n\nSyntaxError: Unexpected token 'else'\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:6:25)","name":"SyntaxError","message":"Unexpected token 'else'"}
[20:44:16 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:44:23 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:44:26 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:44:48 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:45:59 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:46:01 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:46:22 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:46:29 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:46:32 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:46:41 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:46:43 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:47:08 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:47:43 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:47:45 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:48:03 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:48:21 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:48:23 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:48:35 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:48:36 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:48:40 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:271:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:58:11 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\routes\\news.js:171\n    cartCount: req.cart ? Math.max(0, req.cart.getItemCount() || 0) : 0,\n    ^^^^^^^^^\n\nSyntaxError: Unexpected identifier 'cartCount'\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:50:20)","name":"SyntaxError","message":"Unexpected identifier 'cartCount'"}
[21:10:17 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:159:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[21:25:33 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:272:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:35:16 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:272:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[22:27:10 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:270:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:27:10 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:270:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:27:26 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:280:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:27:26 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:280:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:28:32 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:280:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:28:32 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:280:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:28:47 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:280:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:28:47 19/07/2025] [ERROR] Failed to start server | Meta: {"stack":"Error: MongoDB connection failed\n    at D:\\lab_node\\app.js:280:28\n    at D:\\lab_node\\util\\database.js:22:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"MongoDB connection failed"}
[22:29:07 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:299:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[22:33:50 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: authController is not defined\n    at Object.<anonymous> (D:\\lab_node\\routes\\auth.js:14:22)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:59:20)","name":"ReferenceError","message":"authController is not defined"}
[22:34:12 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: authController is not defined\n    at Object.<anonymous> (D:\\lab_node\\routes\\auth.js:14:22)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:59:20)","name":"ReferenceError","message":"authController is not defined"}
[22:34:35 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: authController is not defined\n    at Object.<anonymous> (D:\\lab_node\\routes\\auth.js:14:22)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:59:20)","name":"ReferenceError","message":"authController is not defined"}
[22:35:52 19/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: authController is not defined\n    at Object.<anonymous> (D:\\lab_node\\routes\\auth.js:14:22)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\app.js:59:20)","name":"ReferenceError","message":"authController is not defined"}
[00:55:28 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: asyncHandler is not defined\n    at Object.<anonymous> (D:\\lab_node\\app.js:119:5)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\n    at node:internal/main/run_main_module:36:49","name":"ReferenceError","message":"asyncHandler is not defined"}
[00:55:33 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: asyncHandler is not defined\n    at Object.<anonymous> (D:\\lab_node\\app.js:119:5)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\n    at node:internal/main/run_main_module:36:49","name":"ReferenceError","message":"asyncHandler is not defined"}
[00:55:49 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: asyncHandler is not defined\n    at Object.<anonymous> (D:\\lab_node\\app.js:119:5)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\n    at node:internal/main/run_main_module:36:49","name":"ReferenceError","message":"asyncHandler is not defined"}
[00:56:25 20/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:307:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
